version: '3.8'

services:
  xcorte-frontend:
    build: .
    container_name: xcorte-app
    ports:
      - "80:4000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Opcional: Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: xcorte-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - xcorte-frontend
    restart: unless-stopped
    profiles:
      - ssl
